// Domain kernel for "Verificación de Outbox Pattern y Reduplicación con RabbitMQ Real" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.

export type VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealState = 'PENDING';
export type VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealEventType = 'Orderoutbox' | 'VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealProcessed';

export interface VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealDomainEvent {
  type: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealEventType;
  aggregateId: string;
  version: number;
  occurredOn: Date;
  payload: Record<string, unknown>;
}

export interface VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealCommand {
  /** Identifier of the aggregate the command targets. */
  id: string;
  payload?: Record<string, unknown>;
}

export class DomainValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'DomainValidationError';
  }
}

export class VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealAggregate {
  private _state: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealState = 'PENDING';
  private _version = 0;
  private readonly _events: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealDomainEvent[] = [];

  constructor(public readonly id: string) {
    if (!id || !id.trim()) throw new DomainValidationError('VerificacionDeOutboxPatternYReduplicacionConRabbitMqReal id is required');
  }

  /** Rebuilds an aggregate from persisted state; no events are recorded. */
  static restore(id: string, state: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealState, version: number): VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealAggregate {
    const aggregate = new VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealAggregate(id);
    aggregate._state = state;
    aggregate._version = version;
    return aggregate;
  }

  get state(): VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealState {
    return this._state;
  }

  get version(): number {
    return this._version;
  }

  /** Events recorded since the aggregate was loaded (to be saved via an outbox). */
  get pendingEvents(): readonly VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealDomainEvent[] {
    return this._events;
  }

  processVerificacionDeOutboxPatternYReduplicacionConRabbitMqReal(command: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealCommand): VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealDomainEvent {
    this.assertValid(command);
    return this.record('Orderoutbox', command.payload ?? {});
  }

  private assertValid(command: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealCommand): void {
    if (!command || !command.id || !command.id.trim()) throw new DomainValidationError('Command id is required');
    if (command.id !== this.id) throw new DomainValidationError(`Command targets ${command.id}, not ${this.id}`);
  }

  private record(type: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealEventType, payload: Record<string, unknown>): VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealDomainEvent {
    this._version += 1;
    const event: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealDomainEvent = { type, aggregateId: this.id, version: this._version, occurredOn: new Date(), payload };
    this._events.push(event);
    return event;
  }
}
