// cucumber-js step definitions for "Verificación de Outbox Pattern y Reduplicación con RabbitMQ Real" (generated by gherkin-ai).
// Each step is wired to the feature and returns 'pending' until implemented.
import { Given, When, Then, Before } from '@cucumber/cucumber';
import { VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealAggregate } from '../../src/verificacion-de-outbox-pattern-y-reduplicacion-con-rabbit-mq-real/domain/verificacion-de-outbox-pattern-y-reduplicacion-con-rabbit-mq-real.aggregate';

interface World {
  aggregate?: VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealAggregate;
}

Before(function (this: World) {
  this.aggregate = new VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealAggregate('scenario-aggregate');
});

Given('que el contenedor de RabbitMQ está activo y saludable en `amqp:\\/\\/rabbitmq:5672`', function (this: World) {
  // Pending (given_que_el_contenedor_de_rabbit_mq_esta_activo_y_saludable_en_amqp_rabbitmq_56): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});

When('se inserta un evento de pedido en la tabla Outbox "order_outbox" de PostgreSQL', function (this: World) {
  // Pending (when_se_inserta_un_evento_de_pedido_en_la_tabla_outbox_order_outbox_de_postgre_s): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});

When('el proceso Outbox Publisher lee la tabla y publica el mensaje en la cola "order.created.queue"', function (this: World) {
  // Pending (when_el_proceso_outbox_publisher_lee_la_tabla_y_publica_el_mensaje_en_la_cola_or): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});

Then('el consumidor de la cola procesa el mensaje y marca el registro Outbox como "PROCESSED"', function (this: World) {
  // Pending (then_el_consumidor_de_la_cola_procesa_el_mensaje_y_marca_el_registro_outbox_como): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});

When('se fuerza una reentrega del mismo `MessageId` simulated desde RabbitMQ', function (this: World) {
  // Pending (when_se_fuerza_una_reentrega_del_mismo_message_id_simulated_desde_rabbit_mq): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});

Then('el consumidor detecta la llave de idempotencia y rechaza duplicar la operación en DB', function (this: World) {
  // Pending (then_el_consumidor_detecta_la_llave_de_idempotencia_y_rechaza_duplicar_la_operac): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});

Then('la suite de integración de `ghk verify --docker` completa la prueba con código de salida 0', function (this: World) {
  // Pending (then_la_suite_de_integracion_de_ghk_verify_docker_completa_la_prueba_con_codigo_): drive this.aggregate (or the HTTP API) and assert the outcome.
  return 'pending';
});
