/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: Verificación de Outbox Pattern y Reduplicación con RabbitMQ Real
   Architecture: Monolith Architecture (MVC / Monolithic)
   Stack: typescript + nestjs + prisma
   Generated by gherkin-ai CLI v3.0.0-beta.1
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}

export interface Event1 extends IDomainEvent {
  eventType: 'orderoutbox';
  payload: {
    outbox: string;
    cola: string;
    como: string;
  };
}

// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealCommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.object({
    outbox: z.string(),
    cola: z.string(),
    como: z.string()
  })
});

export type VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealCommand = z.infer<typeof VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealCommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface IVerificacionDeOutboxPatternYReduplicacionConRabbitMqRealRepository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
