/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Verificación de Outbox Pattern y Reduplicación con RabbitMQ Real
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealFixture {
  id: string;
  outbox: string;
  cola: string;
  como: string;
}

export function createVerificacionDeOutboxPatternYReduplicacionConRabbitMqRealFixture(): VerificacionDeOutboxPatternYReduplicacionConRabbitMqRealFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    outbox: 'test_value',
    cola: 'test_value',
    como: 'test_value',
  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "que el contenedor de RabbitMQ está activo y saludable en `amqp://rabbitmq:5672`"
];
